
from PyQt5 import QtCore

DEFAULTS = dict(
    camera=dict(camRadius=3.2, camHeightDeg=15, camTiltDeg=0, omegaDegPerSec=20, fov=600),
    geometry=dict(
        topology="uv_sphere",
        R=1.0, lat=64, lon=64, N=4096, phi_g=3.88322,
        R_major=1.2, r_minor=0.45,
        eps1=1.0, eps2=1.0, ax=1.0, ay=1.0, az=1.0,
        geo_level=1, mobius_w=0.4,
        arch_a=0.0, arch_b=0.6, theta_max=6.28318,
        log_a=0.2, log_b=0.15,
        rose_k=4.0,
        sf2_m=6.0, sf2_a=1.0, sf2_b=1.0, sf2_n1=0.5, sf2_n2=0.5, sf2_n3=0.5,
        density_pdf="1",
        poisson_dmin=0.05,
        lissajous_a=3.0, lissajous_b=2.0, lissajous_phase=0.0,
        vogel_k=2.3999632,
        se_n1=1.0, se_n2=1.0,
        half_height=1.0,
        noisy_amp=0.1, noisy_freq=3.0, noisy_gain=1.0, noisy_omega=0.0,
        sph_terms="2,0,0.4;3,2,0.2",
        weight_map="1",
        R_major2=0.8,
        torus_knot_p=3, torus_knot_q=2,
        strip_w=0.4, strip_n=2,
        blob_noise_amp=0.25, blob_noise_scale=2.0,
        gyroid_scale=1.0, gyroid_thickness=0.05, gyroid_c=0.0,
        schwarz_scale=1.0, schwarz_iso=0.0,
        heart_scale=1.0,
        metaballs_centers="0,0,0",
        metaballs_radii="0.6",
        metaballs_iso=1.0,
        polyhedron_data="",
        df_ops="sphere(1.0)",
        sf3_m1=3.0, sf3_m2=3.0, sf3_m3=3.0,
        sf3_n1=0.5, sf3_n2=0.5, sf3_n3=0.5,
        sf3_a=1.0, sf3_b=1.0, sf3_scale=1.0,
        helix_r=0.4, helix_pitch=0.3, helix_turns=3.0,
        lissajous3d_Ax=1.0, lissajous3d_Ay=1.0, lissajous3d_Az=1.0,
        lissajous3d_wx=3.0, lissajous3d_wy=2.0, lissajous3d_wz=5.0,
        lissajous3d_phi=0.0,
        viviani_a=1.0,
        lic_N=12, lic_steps=180, lic_h=0.05,
        stream_N=12, stream_steps=220,
        geo_graph_level=2,
        rgg_nodes=400, rgg_radius=0.2,
        rings_count=5, ring_points=96,
        hex_step=0.2, hex_nx=12, hex_ny=12,
        voronoi_N=50, voronoi_bbox="-1,1,-1,1"
    ),
    appearance=dict(
        color="#00C8FF", colors="#00C8FF@0,#FFFFFF@1", opacity=1.0, px=2.0,
        palette="uniform", paletteK=2,
        h0=200.0, dh=0.0, wh=0.0,
        blendMode="source-over", shape="circle",
        alphaDepth=0.0,
        noiseScale=1.0, noiseSpeed=0.0,
        pxModMode="none", pxModAmp=0.0, pxModFreq=0.0, pxModPhaseDeg=0.0,
    ),
    dynamics=dict(
        rotX=0.0, rotY=0.0, rotZ=0.0, pulseA=0.0, pulseW=1.0,
        pulsePhaseDeg=0.0, rotPhaseDeg=0.0, rotPhaseMode="none"
    ),
    distribution=dict(
        densityMode="uniform",
        sampler="direct",
        dmin=0.0,
        dmin_px=0.0,
        maskMode="none",
        maskSoftness=0.2,
        maskAnimate=0.0,
        noiseDistortion=0.0,
        densityPulse=0.0,
        clusterCount=1,
        clusterSpread=0.0,
        repelForce=0.0,
        noiseWarp=0.0,
        fieldFlow=0.0,
        pr="uniform_area"
    ),
    mask=dict(
        enabled=False, mode="none", angleDeg=30.0,
        bandHalfDeg=20.0, lonCenterDeg=0.0, lonWidthDeg=30.0,
        softDeg=10.0, invert=False
    ),
    system=dict(Nmax=50000, dprClamp=2.0, depthSort=True, transparent=True)
)

TOOLTIPS = {
    "camera.camRadius":"Détermine la distance entre la caméra et le centre de la scène.",
    "camera.camHeightDeg":"Place la caméra plus haut ou plus bas sur son orbite.",
    "camera.camTiltDeg":"Incline la caméra vers le haut ou vers le bas.",
    "camera.omegaDegPerSec":"Fait tourner automatiquement la caméra autour de la scène.",
    "camera.fov":"Contrôle l’angle de vue : petit pour zoomer, grand pour élargir.",
    "geometry.topology":"Sélectionne la forme de base utilisée pour disposer les particules.",
    "geometry.R":"Agrandit ou réduit toute la forme sans changer sa structure.",
    "geometry.lat":"Nombre de bandes horizontales utilisées pour dessiner la forme.",
    "geometry.lon":"Nombre de colonnes verticales utilisées pour dessiner la forme.",
    "geometry.N":"Nombre total de points générés pour les distributions spirales.",
    "geometry.phi_g":"Décalage progressif entre les points pour les spirales naturelles.",
    "geometry.R_major":"Rayon extérieur du tore.",
    "geometry.r_minor":"Épaisseur du tube du tore.",
    "geometry.eps1":"Arrondi la forme superquadrique sur l’axe horizontal.",
    "geometry.eps2":"Arrondi la forme superquadrique sur l’axe vertical.",
    "geometry.ax":"Étire la superquadrique sur l’axe X.",
    "geometry.ay":"Étire la superquadrique sur l’axe Y.",
    "geometry.az":"Étire la superquadrique sur l’axe Z.",
    "geometry.geo_level":"Affinage du maillage de l’icosaèdre.",
    "geometry.mobius_w":"Largeur du ruban pour la bande de Möbius.",
    "geometry.arch_a":"Contrôle le rayon de départ de la spirale d’Archimède.",
    "geometry.arch_b":"Définit l’écartement entre les spires de la spirale d’Archimède.",
    "geometry.theta_max":"Angle total parcouru par les spirales planes.",
    "geometry.log_a":"Facteur d’échelle initiale de la spirale logarithmique.",
    "geometry.log_b":"Taux de croissance exponentielle de la spirale logarithmique.",
    "geometry.rose_k":"Nombre de pétales de la rosace polaire.",
    "geometry.sf2_m":"Paramètre m de la superformule 2D (symétries).",
    "geometry.sf2_a":"Paramètre a de la superformule 2D (échelle horizontale).",
    "geometry.sf2_b":"Paramètre b de la superformule 2D (échelle verticale).",
    "geometry.sf2_n1":"Exposant n1 de la superformule 2D.",
    "geometry.sf2_n2":"Exposant n2 de la superformule 2D.",
    "geometry.sf2_n3":"Exposant n3 de la superformule 2D.",
    "geometry.density_pdf":"Fonction de densité radiale utilisée pour répartir les points sur le disque.",
    "geometry.poisson_dmin":"Distance minimale entre deux points du disque de Poisson.",
    "geometry.lissajous_a":"Fréquence horizontale de la courbe de Lissajous plane.",
    "geometry.lissajous_b":"Fréquence verticale de la courbe de Lissajous plane.",
    "geometry.lissajous_phase":"Décalage de phase (rad) pour la courbe de Lissajous plane.",
    "geometry.vogel_k":"Facteur de rotation entre deux points successifs sur la spirale sphérique.",
    "geometry.se_n1":"Exposant n1 de la superellipsoïde.",
    "geometry.se_n2":"Exposant n2 de la superellipsoïde.",
    "geometry.half_height":"Facteur d’écrasement de la demi-sphère.",
    "geometry.noisy_amp":"Amplitude du bruit radial appliqué à la sphère.",
    "geometry.noisy_freq":"Fréquence du bruit sphérique.",
    "geometry.noisy_gain":"Gain multiplicatif du bruit fractal.",
    "geometry.noisy_omega":"Déphasage angulaire du bruit sphérique.",
    "geometry.sph_terms":"Liste de termes l,m,amplitude pour les harmoniques sphériques (format l,m,a).",
    "geometry.weight_map":"Expression pondérant la densité de points sur la sphère (variables theta,phi).",
    "geometry.R_major2":"Rayon majeur du second tore concentrique.",
    "geometry.torus_knot_p":"Nombre d’enroulements autour de l’axe majeur du nœud torique.",
    "geometry.torus_knot_q":"Nombre d’enroulements autour du tube du nœud torique.",
    "geometry.strip_w":"Largeur du ruban torsadé.",
    "geometry.strip_n":"Nombre de torsions complètes du ruban.",
    "geometry.blob_noise_amp":"Amplitude de la perturbation bruitée d’un blob.",
    "geometry.blob_noise_scale":"Échelle spatiale du bruit appliqué au blob.",
    "geometry.gyroid_scale":"Échelle spatiale de la surface de gyroid.",
    "geometry.gyroid_thickness":"Épaisseur de la coquille autour de l’isosurface du gyroid.",
    "geometry.gyroid_c":"Décalage de l’iso-valeur du gyroid.",
    "geometry.schwarz_scale":"Échelle de la surface minimale de Schwarz.",
    "geometry.schwarz_iso":"Valeur iso utilisée pour l’extraction de la surface de Schwarz.",
    "geometry.heart_scale":"Échelle globale de la forme de cœur implicite.",
    "geometry.polyhedron_data":"Définition personnalisée d’un polyèdre (JSON vertices/faces).",
    "geometry.metaballs_centers":"Liste des centres des métaballes (x,y,z séparés par des virgules).",
    "geometry.metaballs_radii":"Rayons associés aux métaballes (séparés par des virgules).",
    "geometry.metaballs_iso":"Seuil iso-surface pour les métaballes.",
    "geometry.df_ops":"Script de combinaisons SDF (sphere(r), box(x,y,z), union(a,b), sub(a,b), etc.).",
    "geometry.sf3_m1":"Paramètre m1 de la superformule 3D.",
    "geometry.sf3_m2":"Paramètre m2 de la superformule 3D.",
    "geometry.sf3_m3":"Paramètre m3 de la superformule 3D.",
    "geometry.sf3_n1":"Exposant n1 de la superformule 3D.",
    "geometry.sf3_n2":"Exposant n2 de la superformule 3D.",
    "geometry.sf3_n3":"Exposant n3 de la superformule 3D.",
    "geometry.sf3_a":"Paramètre a (échelle latitude) de la superformule 3D.",
    "geometry.sf3_b":"Paramètre b (échelle longitude) de la superformule 3D.",
    "geometry.sf3_scale":"Facteur global appliqué à la superformule 3D.",
    "geometry.helix_r":"Rayon de l’hélice 3D.",
    "geometry.helix_pitch":"Pas vertical de l’hélice par tour.",
    "geometry.helix_turns":"Nombre de tours de l’hélice.",
    "geometry.lissajous3d_Ax":"Amplitude suivant X pour la courbe de Lissajous 3D.",
    "geometry.lissajous3d_Ay":"Amplitude suivant Y pour la courbe de Lissajous 3D.",
    "geometry.lissajous3d_Az":"Amplitude suivant Z pour la courbe de Lissajous 3D.",
    "geometry.lissajous3d_wx":"Fréquence suivant X de la courbe de Lissajous 3D.",
    "geometry.lissajous3d_wy":"Fréquence suivant Y de la courbe de Lissajous 3D.",
    "geometry.lissajous3d_wz":"Fréquence suivant Z de la courbe de Lissajous 3D.",
    "geometry.lissajous3d_phi":"Décalage de phase commun des composantes de Lissajous 3D.",
    "geometry.viviani_a":"Rayon du tore générateur de la courbe de Viviani.",
    "geometry.lic_N":"Nombre de lignes intégrées sur la sphère.",
    "geometry.lic_steps":"Nombre d’étapes d’intégration pour chaque ligne LIC.",
    "geometry.lic_h":"Pas de temps utilisé pour l’intégration LIC.",
    "geometry.stream_N":"Nombre de lignes intégrées sur le tore.",
    "geometry.stream_steps":"Nombre d’étapes pour l’intégration sur le tore.",
    "geometry.geo_graph_level":"Niveau de subdivision du graphe géodésique.",
    "geometry.rgg_nodes":"Nombre de points du graphe géométrique aléatoire.",
    "geometry.rgg_radius":"Distance de connexion pour le graphe géométrique aléatoire.",
    "geometry.rings_count":"Nombre d’anneaux concentriques générés.",
    "geometry.ring_points":"Nombre de points par anneau.",
    "geometry.hex_step":"Espacement entre les points du pavage hexagonal.",
    "geometry.hex_nx":"Nombre de colonnes du pavage hexagonal.",
    "geometry.hex_ny":"Nombre de lignes du pavage hexagonal.",
    "geometry.voronoi_N":"Nombre de graines utilisées pour le diagramme de Voronoï.",
    "geometry.voronoi_bbox":"Boîte englobante (xmin,xmax,ymin,ymax) pour les graines de Voronoï.",
    "appearance.color":"Couleur principale des particules.",
    "appearance.colors":"Couleurs listées avec leur position pour créer un dégradé personnalisé.",
    "appearance.opacity":"Rend les particules plus ou moins transparentes.",
    "appearance.px":"Taille moyenne des particules en pixels.",
    "appearance.palette":"Mode d’attribution des couleurs.",
    "appearance.paletteK":"Fréquence de répétition du motif dans les palettes répétées.",
    "appearance.blendMode":"Définit comment les particules se mélangent entre elles et avec le fond.",
    "appearance.shape":"Choix de la forme de chaque particule.",
    "appearance.alphaDepth":"Atténue la visibilité des particules éloignées.",
    "appearance.h0":"Couleur de départ pour les palettes HSL animées.",
    "appearance.dh":"Amplitude de variation de la couleur pour les palettes HSL.",
    "appearance.wh":"Vitesse à laquelle la couleur HSL change.",
    "appearance.noiseScale":"Taille des détails colorés générés par le bruit.",
    "appearance.noiseSpeed":"Vitesse d’animation de ces détails colorés.",
    "appearance.pxModMode":"Active les variations automatiques de taille.",
    "appearance.pxModAmp":"Amplitude maximale des variations de taille.",
    "appearance.pxModFreq":"Rythme de répétition des variations de taille.",
    "appearance.pxModPhaseDeg":"Décalage du motif de variation de taille.",
    "dynamics.rotX":"Fait tourner le nuage autour de l’axe horizontal X.",
    "dynamics.rotY":"Fait tourner le nuage autour de l’axe vertical Y.",
    "dynamics.rotZ":"Fait tourner le nuage autour de l’axe longitudinal Z.",
    "dynamics.pulseA":"Amplitude de l’effet de respiration.",
    "dynamics.pulseW":"Vitesse de l’effet de respiration.",
    "dynamics.pulsePhaseDeg":"Décalage initial de l’animation de respiration.",
    "dynamics.rotPhaseMode":"Répartit un décalage de rotation selon l’index ou le rayon des particules.",
    "dynamics.rotPhaseDeg":"Amplitude maximale du décalage de rotation.",
    "distribution.densityMode":"Contrôle la pondération globale des points (uniforme, centre, bord, bruit).",
    "distribution.sampler":"Méthode de sous-échantillonnage à appliquer sur la géométrie générée.",
    "distribution.dmin":"Impose une distance minimale en 3D pour limiter les amas de points.",
    "distribution.dmin_px":"Évite que deux particules ne se projettent trop proches l’une de l’autre.",
    "distribution.maskMode":"Applique un masque spatial (calotte, bande, zone aléatoire).",
    "distribution.maskSoftness":"Élargit la transition du masque pour un bord plus doux.",
    "distribution.maskAnimate":"Anime le masque pour faire se déplacer la zone visible.",
    "distribution.noiseDistortion":"Déforme les positions selon un champ de bruit statique.",
    "distribution.densityPulse":"Fait pulser la distribution en contractant/étirant le nuage.",
    "distribution.clusterCount":"Nombre de groupes privilégiés pour la répartition.",
    "distribution.clusterSpread":"Détermine à quel point les points sont aspirés vers leurs centres de groupe.",
    "distribution.repelForce":"Force de répulsion locale pour lisser les amas restants.",
    "distribution.noiseWarp":"Amplitude de la déformation animée par le bruit.",
    "distribution.fieldFlow":"Intensité du champ de rotation appliqué aux positions.",
    "mask.enabled":"Active ou désactive le masquage des particules.",
    "mask.mode":"Définit la zone conservée ou masquée.",
    "mask.angleDeg":"Ouvre plus ou moins le masque en forme de calotte.",
    "mask.bandHalfDeg":"Largeur d’une demi-bande autour de l’équateur.",
    "mask.lonCenterDeg":"Centre le masque longitudinal.",
    "mask.lonWidthDeg":"Largeur totale du masque longitudinal.",
    "mask.softDeg":"Adoucit le bord du masque pour un fondu progressif.",
    "mask.invert":"Inverse la zone masquée et visible.",
    "system.Nmax":"Nombre maximum de particules autorisées simultanément.",
    "system.dprClamp":"Limite la résolution utilisée pour protéger les performances.",
    "system.depthSort":"Trie les particules pour un affichage correct avec la transparence.",
    "system.transparent":"Permet de rendre la fenêtre de prévisualisation transparente."
}
